### ISSUE TITLE
Adress already in use. What will i do?

### ISSUE THREAD

**Issue by Arkdevnoder** [jython234/BouncyBall#9]
ound BouncyBall jar.
[08:00:18] [MCPE-Proxy/INFO] [BouncyBall]: BouncyBall version v1.0-SNAPSHOT, implementing MCPE 0.10.4 protocol 20
[08:00:18] [MCPE-Proxy/INFO] [BouncyBall]: Logging Packet Decode errors to console: true
[08:00:18] [MCPE-Proxy/INFO] [BouncyBall]: Server started on port 19132
[08:00:41] [MCPE-Proxy/DEBUG] [BouncyBall]: Accepting new client session from /185.11.4.128:19132
[08:00:41] [RemoteServer-/185.11.4.128:19132/ERROR] [BouncyBall]: SocketException: Address already in use
java.net.BindException: Address already in use
at java.net.PlainDatagramSocketImpl.bind0(Native Method)
at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:94)
at java.net.DatagramSocket.bind(DatagramSocket.java:392)
at java.net.DatagramSocket.(DatagramSocket.java:242)
at java.net.DatagramSocket.(DatagramSocket.java:299)
at java.net.DatagramSocket.(DatagramSocket.java:271)
at net.beaconpe.bouncyball.session.RemoteServerSession.run(RemoteServerSession.java:51)

**Comment by DegenApeDev** [comment]
Yeah what to do now?? Is this even working??

**Comment by alejzeis** [comment]
You have two servers running on the same port. Btw the master branch is old
and doesnt work well. Im working on rewriting the proxy in TypeScript with
nodeJS, that should be on the "ts" branch.
